name: Node.js Runner

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
       npm ci
       touch .env
       echo "${{ secrets.PROD_ENV_FILE }}" > .env

    - run: |
        pm2 start ecosystem.config.js --env production

        
    
