name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the project (if necessary)
      run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }} # EC2 IP address stored as a secret
        username: ${{ secrets.EC2_USER }}  # Username to log into EC2 (e.g., ubuntu)
        key: ${{ secrets.EC2_KEY }}  # Private SSH key for the EC2 instance
        script: |
          cd life_drop_backend/
          git pull origin main  # Pull latest changes from GitHub
          npm install  # Install dependencies
          pm2 restart all  # Restart your Node.js application using PM2
